### ISSUE TITLE
"Failed connecting to SNS" error when trying to --dry-run

### ISSUE THREAD

**Issue by clarkenheim** [sebdah/dynamic-dynamodb#184]
Hi @sebdah 

I repeatedly get this bellow error when trying to --dry-run my dynamic-dynamodb.conf
Is there anything obvious that would cause this error that i am missing?
My dynamic-dynamodb.conf file has anything to do with SNS commented out, which is why i am struggling with this error.

dynamic-dynamodb --dry-run
2014-06-05 14:26:59,035 - dynamic-dynamodb - ERROR - dryrun - Failed connecting to SNS: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
2014-06-05 14:26:59,035 - dynamic-dynamodb - ERROR - dryrun - Please report an issue at: https://github.com/sebdah/dynamic-dynamodb/issues
Traceback (most recent call last):
  File "/usr/bin/dynamic-dynamodb", line 22, in <module>
    import dynamic_dynamodb
  File "/usr/lib/python2.6/site-packages/dynamic_dynamodb/**init**.py", line 29, in <module>
    from dynamic_dynamodb.aws import dynamodb
  File "/usr/lib/python2.6/site-packages/dynamic_dynamodb/aws/dynamodb.py", line 19, in <module>
    from dynamic_dynamodb.aws import sns
  File "/usr/lib/python2.6/site-packages/dynamic_dynamodb/aws/sns.py", line 124, in <module>
    SNS_CONNECTION = **get_connection_SNS()
  File "/usr/lib/python2.6/site-packages/dynamic_dynamodb/aws/sns.py", line 112, in __get_connection_SNS
    connection = sns.connect_to_region(region)
  File "/usr/lib/python2.6/site-packages/boto/sns/__init**.py", line 53, in connect_to_region
    return region.connect(*_kw_params)
  File "/usr/lib/python2.6/site-packages/boto/regioninfo.py", line 188, in connect
    return self.connection_cls(region=self, *_kw_params)
  File "/usr/lib/python2.6/site-packages/boto/sns/connection.py", line 76, in **init**
    profile_name=profile_name)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1073, in **init**
    profile_name=profile_name)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 572, in **init**
    host, config, self.provider, self._required_auth_capability())
  File "/usr/lib/python2.6/site-packages/boto/auth.py", line 883, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))

**Comment by IgalSc** [comment]
I have the same issue
my dynamic-dynamodb.conf has everything SNS related uncommented.
My IAM policy has the correct SNS arn

Still, starting the dynamic-dynamodb fails with the following:

2015-07-28 14:14:23,229 - dynamic-dynamodb - ERROR - Failed connecting to SNS: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
2015-07-28 14:14:23,230 - dynamic-dynamodb - ERROR - Please report an issue at: https://github.com/sebdah/dynamic-dynamodb/issues
Traceback (most recent call last):
  File "/home/ubuntu/dynamic-dynamodb/dynamic-dynamodb", line 22, in <module>
    import dynamic_dynamodb
  File "/home/ubuntu/dynamic-dynamodb/dynamic_dynamodb/__init__.py", line 29, in <module>
    from dynamic_dynamodb.aws import dynamodb
  File "/home/ubuntu/dynamic-dynamodb/dynamic_dynamodb/aws/dynamodb.py", line 18, in <module>
    from dynamic_dynamodb.aws import sns
  File "/home/ubuntu/dynamic-dynamodb/dynamic_dynamodb/aws/sns.py", line 123, in <module>
    SNS_CONNECTION = __get_connection_SNS()
  File "/home/ubuntu/dynamic-dynamodb/dynamic_dynamodb/aws/sns.py", line 111, in __get_connection_SNS
    connection = sns.connect_to_region(region)
  File "/usr/local/lib/python2.7/dist-packages/boto/sns/__init__.py", line 53, in connect_to_region
    return region.connect(**kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/regioninfo.py", line 187, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/sns/connection.py", line 76, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python2.7/dist-packages/boto/auth.py", line 987, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
