### ISSUE TITLE
Install doesn't appear to work on Ubuntu

### ISSUE THREAD

**Issue by chrischolette** [sebdah/dynamic-dynamodb#218]
Using pip or github clone, I get the following error.  Any leads?

ubuntu@ip-10-251-35-4:~$ dynamic-dynamodb -c dynamic-dynamodb.conf
Traceback (most recent call last):
  File "/usr/local/bin/dynamic-dynamodb", line 5, in <module>
    pkg_resources.run_script('dynamic-dynamodb==1.19.0', 'dynamic-dynamodb')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/dynamic_dynamodb-1.19.0-py2.7.egg/EGG-INFO/scripts/dynamic-dynamodb", line 22, in <module>
    import dynamic_dynamodb
  File "/usr/local/lib/python2.7/dist-packages/dynamic_dynamodb-1.19.0-py2.7.egg/dynamic_dynamodb/**init**.py", line 30, in <module>
    from dynamic_dynamodb.core import gsi, table
  File "/usr/local/lib/python2.7/dist-packages/dynamic_dynamodb-1.19.0-py2.7.egg/dynamic_dynamodb/core/gsi.py", line 8, in <module>
    from dynamic_dynamodb.statistics import gsi as gsi_stats
  File "/usr/local/lib/python2.7/dist-packages/dynamic_dynamodb-1.19.0-py2.7.egg/dynamic_dynamodb/statistics/gsi.py", line 157, in <module>
    stop_max_attempt_number=10)
  File "build/bdist.linux-x86_64/egg/retrying.py", line 47, in wrap
AttributeError: 'module' object has no attribute 'wraps'

**Comment by bounav** [comment]
Had that issue on Mac OS X `10.10.1` running version `1.20.2` of `dynamic-dynamodb`.

pip installed the latest version of retrying (1.3.3) so I ended up downgrading to version 1.2.3 of retrying and now dynamic-dynamodb runs...

    sudo -H pip install retrying==1.2.3
