### ISSUE TITLE
Logging an AccessDeniedException in dynamodb.update_table_provisioning causing a KeyError

### ISSUE THREAD

**Issue by craiga** [sebdah/dynamic-dynamodb#247]
When I don't have permission to `dynamodb:UpdateTable` on `my_table`, I get a `KeyError` instead of a message telling me about an `AccessDeniedException`.

```
$ dynamic-dynamodb --config my-config.ini 
2015-06-01 01:13:40,628 - dynamic-dynamodb - INFO - my_table - Consumed read units: 150%
2015-06-01 01:13:40,673 - dynamic-dynamodb - INFO - my_table - Consumed write units: 0%
2015-06-01 01:13:40,723 - dynamic-dynamodb - INFO - my_table - Consumed read units: 150%
2015-06-01 01:13:40,742 - dynamic-dynamodb - INFO - my_table - Read throttle count: 402
2015-06-01 01:13:40,743 - dynamic-dynamodb - INFO - my_table - Resetting the number of consecutive read checks. Reason: scale up event detected
2015-06-01 01:13:40,743 - dynamic-dynamodb - INFO - my_table - Consecutive read checks 0/1
2015-06-01 01:13:40,787 - dynamic-dynamodb - INFO - my_table - Consumed write units: 0%
2015-06-01 01:13:40,816 - dynamic-dynamodb - INFO - my_table - Write throttle count: 0
2015-06-01 01:13:40,816 - dynamic-dynamodb - INFO - my_table - Scaling down writes is not done when usage is at 0%
2015-06-01 01:13:40,816 - dynamic-dynamodb - INFO - my_table - Consecutive write checks 0/1
2015-06-01 01:13:40,816 - dynamic-dynamodb - INFO - my_table - Changing provisioning to 25 read units and 1 write units
2015-06-01 01:13:40,877 - dynamic-dynamodb - INFO - my_table - Updating provisioning to 25 reads and 1 writes
2015-06-01 01:13:40,882 - dynamic-dynamodb - ERROR - 'message'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/dynamic_dynamodb/__init__.py", line 98, in main
    execute()
  File "/usr/local/lib/python2.7/site-packages/dynamic_dynamodb/__init__.py", line 131, in execute
    table_num_consec_write_checks)
  File "/usr/local/lib/python2.7/site-packages/dynamic_dynamodb/core/table.py", line 68, in ensure_provisioning
    updated_write_units)
  File "/usr/local/lib/python2.7/site-packages/dynamic_dynamodb/core/table.py", line 576, in __update_throughput
    int(write_units))
  File "/usr/local/lib/python2.7/site-packages/dynamic_dynamodb/aws/dynamodb.py", line 385, in update_table_provisioning
    ).format(table_name, exception, error.body['message']))
KeyError: 'message'
```

**Comment by sebdah** [comment]
This should be fixed now in version 1.20.6. Thanks for the bug report!
