### ISSUE TITLE
"Failed connecting to SNS"

### ISSUE THREAD

**Issue by IgalSc** [sebdah/dynamic-dynamodb#255]
This is dublicate(?) of https://github.com/sebdah/dynamic-dynamodb/issues/184

Fresh install of dynamic-dynamodb on Ubuntu 14.04
my dynamic-dynamodb.conf has everything SNS related uncommented.
My IAM policy has the correct SNS arn

Still, starting the dynamic-dynamodb fails with the following:

```
2015-07-28 14:14:23,229 - dynamic-dynamodb - ERROR - Failed connecting to SNS: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
2015-07-28 14:14:23,230 - dynamic-dynamodb - ERROR - Please report an issue at: https://github.com/sebdah/dynamic-dynamodb/issues
Traceback (most recent call last):
File "/home/ubuntu/dynamic-dynamodb/dynamic-dynamodb", line 22, in 
import dynamic_dynamodb
File "/home/ubuntu/dynamic-dynamodb/dynamic_dynamodb/init.py", line 29, in 
from dynamic_dynamodb.aws import dynamodb
File "/home/ubuntu/dynamic-dynamodb/dynamic_dynamodb/aws/dynamodb.py", line 18, in 
from dynamic_dynamodb.aws import sns
File "/home/ubuntu/dynamic-dynamodb/dynamic_dynamodb/aws/sns.py", line 123, in 
SNS_CONNECTION = get_connection_SNS()
File "/home/ubuntu/dynamic-dynamodb/dynamic_dynamodb/aws/sns.py", line 111, in __get_connection_SNS
connection = sns.connect_to_region(region)
File "/usr/local/lib/python2.7/dist-packages/boto/sns/__init.py", line 53, in connect_to_region
return region.connect(*kw_params)
File "/usr/local/lib/python2.7/dist-packages/boto/regioninfo.py", line 187, in connect
return self.connection_cls(region=self, *kw_params)
File "/usr/local/lib/python2.7/dist-packages/boto/sns/connection.py", line 76, in init
profile_name=profile_name)
File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1100, in init
provider=provider)
File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 569, in init
host, config, self.provider, self._required_auth_capability())
File "/usr/local/lib/python2.7/dist-packages/boto/auth.py", line 987, in get_auth_handler
'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
```

**Comment by IgalSc** [comment]
can anyone please look into it?

**Comment by sebdah** [comment]
Closing as too old. Sorry.
