### ISSUE TITLE
Unhandled exception: ValidationException

### ISSUE THREAD

**Issue by fwachsmuth** [sebdah/dynamic-dynamodb#28]
```
ubuntu@helo:~$ sudo dynamic-dynamodb -c PROD_AccountCounts.conf
2013-04-11 07:34:45,617 - dynamic-dynamodb - INFO - Consumed reads: 34
2013-04-11 07:34:45,630 - dynamic-dynamodb - INFO - Provisioned reads: 200
2013-04-11 07:34:45,630 - dynamic-dynamodb - INFO - Consumed read capacity: 17%
2013-04-11 07:34:45,630 - dynamic-dynamodb - INFO - Reads lower threshold: 30%
2013-04-11 07:34:45,630 - dynamic-dynamodb - INFO - Reads upper threshold: 80%
2013-04-11 07:34:45,666 - dynamic-dynamodb - INFO - Consumed writes: 7
2013-04-11 07:34:45,680 - dynamic-dynamodb - INFO - Provisioned writes: 18
2013-04-11 07:34:45,680 - dynamic-dynamodb - INFO - Consumed write capacity: 39%
2013-04-11 07:34:45,681 - dynamic-dynamodb - INFO - Writes lower threshold: 30%
2013-04-11 07:34:45,681 - dynamic-dynamodb - INFO - Writes upper threshold: 95%
2013-04-11 07:34:45,720 - dynamic-dynamodb - INFO - Reached provisioned reads min limit: 200
2013-04-11 07:34:45,720 - dynamic-dynamodb - INFO - Changing provisioning to 200 reads and 18 writes
Traceback (most recent call last):
  File "/usr/local/bin/dynamic-dynamodb", line 7, in <module>
    main.main()
  File "/usr/local/lib/python2.6/dist-packages/dynamic_dynamodb/main.py", line 229, in main
    dynamic_ddb.run()
  File "/usr/local/lib/python2.6/dist-packages/dynamic_dynamodb/dynamic_dynamodb.py", line 146, in run
    self.ensure_proper_provisioning()
  File "/usr/local/lib/python2.6/dist-packages/dynamic_dynamodb/dynamic_dynamodb.py", line 210, in ensure_proper_provisioning
    throughput['write_units'])
  File "/usr/local/lib/python2.6/dist-packages/dynamic_dynamodb/dynamic_dynamodb.py", line 483, in _update_throughput
    table.update_throughput(int(read_units), int(write_units))
  File "/usr/local/lib/python2.6/dist-packages/boto/dynamodb/table.py", line 245, in update_throughput
    self.layer2.update_throughput(self, read_units, write_units)
  File "/usr/local/lib/python2.6/dist-packages/boto/dynamodb/layer2.py", line 405, in update_throughput
    'WriteCapacityUnits': write_units})
  File "/usr/local/lib/python2.6/dist-packages/boto/dynamodb/layer1.py", line 261, in update_table
    return self.make_request('UpdateTable', json_input)
  File "/usr/local/lib/python2.6/dist-packages/boto/dynamodb/layer1.py", line 118, in make_request
    retry_handler=self._retry_handler)
  File "/usr/local/lib/python2.6/dist-packages/boto/connection.py", line 845, in _mexe
    status = retry_handler(response, i, next_sleep)
  File "/usr/local/lib/python2.6/dist-packages/boto/dynamodb/layer1.py", line 155, in _retry_handler
    response.status, response.reason, data)
boto.dynamodb.exceptions.DynamoDBValidationError: DynamoDBValidationError: 400 Bad Request
{'message': 'The provisioned throughput for the table will not change. The requested value equals the current value. Current ReadCapacityUnits provisioned for the table: 200. Requested ReadCapacityUnits: 200. Current WriteCapacityUnits provisioned for the table: 18. Requested WriteCapacityUnits: 18. Refer to the Amazon DynamoDB Developer Guide for current limits and how to request higher limits.', '__type': 'com.amazon.coral.validate#ValidationException'}
ubuntu@helo:~$ 
```

**Comment by ankushsachdeva** [comment]
I am having this issue on v2.1.0 with GSI

ubuntu@ip-xxx:~/dynamic-dynamodb$ ./dynamic-dynamodb -c dynamic-dynamodb.conf 
2015-10-04 20:35:33,226 - dynamic-dynamodb - INFO - tagPosts - Consumed read units: 0.00%
2015-10-04 20:35:33,706 - dynamic-dynamodb - INFO - tagPosts - Consumed write units: 0.00%
2015-10-04 20:35:34,463 - dynamic-dynamodb - INFO - tagPosts - Consumed read units: 0.00%
2015-10-04 20:35:34,697 - dynamic-dynamodb - INFO - tagPosts - Read throttle count: 0
2015-10-04 20:35:35,173 - dynamic-dynamodb - INFO - tagPosts - Throttled read percent by provision: 0.00%
2015-10-04 20:35:35,638 - dynamic-dynamodb - INFO - tagPosts - Throttled read percent by consumption: 0.00%
2015-10-04 20:35:35,638 - dynamic-dynamodb - INFO - tagPosts - Scaling down reads is not done when usage is at 0%
2015-10-04 20:35:35,638 - dynamic-dynamodb - INFO - tagPosts - Consecutive read checks 0/1
2015-10-04 20:35:36,343 - dynamic-dynamodb - INFO - tagPosts - Consumed write units: 0.00%
2015-10-04 20:35:36,601 - dynamic-dynamodb - INFO - tagPosts - Write throttle count: 0
2015-10-04 20:35:37,070 - dynamic-dynamodb - INFO - tagPosts - Throttled write percent by provision: 0.00%
2015-10-04 20:35:37,547 - dynamic-dynamodb - INFO - tagPosts - Throttled write percent by consumption: 0.00%
2015-10-04 20:35:37,547 - dynamic-dynamodb - INFO - tagPosts - Scaling down writes is not done when usage is at 0%
2015-10-04 20:35:37,547 - dynamic-dynamodb - INFO - tagPosts - Consecutive write checks 0/1
2015-10-04 20:35:37,548 - dynamic-dynamodb - INFO - tagPosts - No need to change provisioning
2015-10-04 20:35:37,795 - dynamic-dynamodb - INFO - tagPosts - Will ensure provisioning for global secondary index tagId-postPostedOn-index
2015-10-04 20:35:38,272 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Consumed read units: 0.00%
2015-10-04 20:35:38,747 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Consumed write units: 0.00%
2015-10-04 20:35:39,458 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Consumed read units: 0.00%
2015-10-04 20:35:39,701 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Read throttle count: 0
2015-10-04 20:35:40,176 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Throttled read percent by provision: 0.00%
2015-10-04 20:35:40,653 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Throttled read percent by consumption: 0.00%
2015-10-04 20:35:40,654 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Increasing reads tomeet gsi-min-provisioned-reads limit (10 reads)
2015-10-04 20:35:40,654 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Consumed is over proposed read units. Will leave table at current setting.
2015-10-04 20:35:40,654 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Consecutive read checks 0/1
2015-10-04 20:35:41,360 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Consumed write units: 0.00%
2015-10-04 20:35:41,610 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Write throttle count: 0
2015-10-04 20:35:42,090 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Throttled write percent by provision: 0.00%
2015-10-04 20:35:42,587 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Throttled write percent by consumption: 0.00%
2015-10-04 20:35:42,587 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Increasing writes tomeet gsi-min-provisioned-writes limit (10 writes)
2015-10-04 20:35:42,587 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Consumed is over proposed write units. Will leave table at current setting.
2015-10-04 20:35:42,587 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Consecutive write checks 0/1
2015-10-04 20:35:42,587 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Changing provisioning to 1.000000 read units and 1.000000 write units
2015-10-04 20:35:43,778 - dynamic-dynamodb - INFO - tagPosts - GSI: tagId-postPostedOn-index - Updating provisioning to 1 reads and 1 writes
2015-10-04 20:35:44,015 - dynamic-dynamodb - ERROR - tagPosts - GSI: tagId-postPostedOn-index - Unhandled exception: ValidationException: The provisioned throughput for the index tagId-postPostedOn-index will not change. The requested value equals the current value. Current ReadCapacityUnits provisioned for index tagId-postPostedOn-index: 1. Requested ReadCapacityUnits: 1. Current WriteCapacityUnits provisioned for index tagId-postPostedOn-index: 1. Requested WriteCapacityUnits: 1. Refer to the Amazon DynamoDB Developer Guide for current limits and how to request higher limits.. Please file a bug report at https://github.com/sebdah/dynamic-dynamodb/issues

**Comment by sebdah** [comment]
@ankushsachdeva Thanks for the report. I have started looking at the issue, but need more information from one contributor. Please continue all discussion in issue #277.
